baseURL = 'https://andrey-bychkov77.github.io/'
languageCode = 'ru'
title = 'Андрей Бычков'
defaultContentLanguage = 'ru'
publishDir = 'docs'

[params]
  description = 'Андрей Бычков - российский альпинист, кандидат в мастера спорта'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableHTML = false
  [minify.tdewolff.html]
    keepWhitespace = true