baseURL = 'https://andrey-bychkov77.github.io/'
languageCode = 'ru'
title = 'Андрей Бычков'
defaultContentLanguage = 'ru'
publishDir = 'docs'

[caches]
  [caches.getjson]
    maxAge = -1
  [caches.getcsv]
    maxAge = -1
  [caches.getresource]
    maxAge = -1

[params]
  description = 'Андрей Бычков - российский альпинист, кандидат в мастера спорта'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[minify]
  disableHTML = false
  [minify.tdewolff.html]
    keepWhitespace = true